# Generated by Django 4.2.7 on 2023-11-07 17:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="bcc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="cc",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, null=True, size=None
            ),
        ),
    ]
